
export const baseBoard = {
   carStart: playerCount => playerCount >= 3 ? { x: 11, y: 23 } : { x: 11, y: 17 },
   map: `
oowowowowowooesooottttt
wooooooooowowsswwowowwo
eowwowowwooowsswooooooe
wowooooowowoossoowowoww
oooowowooooowsswooooooo
owwowowwowowwssoowwowwo
sssssssssssssxxwowooooo
sssssssssssssxxoooowwow
wowwowowwowowsswowooooo
ooowooowooooossoooowowo
owoooEoooccowsswwowwowo
owowoooFoccooxxssssssss
ooooowoooooowxxssssssss
woDowwwowwowwsswwowoXow
sssssssssxxssxxooowoooo
sssssssssxxssxxwwowwoWo
woBowowowsswowooooooooo
oooooooowsswoooSoToUoVo
oAoCowwoossoowooooooooo
oooooowowsswowwowowowow
wowowooooxxssssssssssss
wowowwowwxxssssssssssss
sssssssssyywowowowwowwo
sssssssssyywoooooowoooo
owwowwowwssoowwoNoooQow
oowoooooosswoowooowoooo
woooIoJowsswwooowowwowo
woHooooowssooowoooooowo
oooowoKoosswowwoOowwooo
oGowwoooLsswoooooooooRo
oooooowoossooMowoPowooo
owwowowowsswooowooowowo
`
}
//ABCDEF
//GHIJKL
//MNOPQR
//STUVWX
export const bcBoard = {
   carStart: () => ({ x: 11, y: 17 }),
   map: `
oowwwowowoosesswowwowwe
wooooooooowsswowooooowo
eowwowowwoosswooowowowo
wooooooowowssoowooooooo
wowowowooowsswowowowwow
eooooooowoossoooowooooo
wowowwowwowsswwowwwowow
ooooowxxsssxxssxxssssss
owowooxxsssxxssxxssssss
owooowsswwowowwsswowowo
ooowoosswooooowssoowowo
wowwowssoowoSoosswooooo
ssssssxxwoooooTssooVoUo
ssssssxxoowowoosswooooo
wowowwsswowowowssoowwow
ooooowxxsssssssxxwooooo
oAowowxxsssssssxxooWoXo
ooowoosswowwoccsswooooo
oBooowssoowwoccsswwowow
oooDoossEooooooxxssssss
oCooowssooFowowxxssssss
ooowoosswoooooosswowoMo
wowwowsswwowowwssoowooo
ssssssxxsssxxssxxwooowo
ssssssxxsssxxssxxwoNowo
owowowowowwsswowooooooo
oooooooooowsswooowwoOow
woGoHowoIoossooPooooooo
oooooooooowsswooowowowo
oJoKowwoLoossooQowooooo
oooooooooowsswoooooRowo
owowwowowoossoowowooooo
`
}
